### ISSUE TITLE
Syrupy removes other snapshot files in the same snapshot directory

### ISSUE THREAD

**Issue by lime-green** [tophat/syrupy#119]
**Describe the bug**
Syrupy removes other snapshot files in the same snapshot directory

**To Reproduce**
1. Have two test files (`test_file1.py`, `test_file2.py`) in the same directory where each one has a snapshot assertion
2. Generate snapshots `pytest --snapshot-update` see two snapshot files
2. `pytest  test_file1.py --snapshot-update`
3. See only one snapshot file

**Expected behavior**
Syrupy should update the file for the file under test and not remove the other snapshot file

**Desktop (please complete the following information):**
 - OS: macOS 
 - Version 10.15.2 (Catalina)

**Comment by noahnu** [comment]
We choose which snapshots to delete by comparing visited test cases/files to "discovered" test cases/files.

When running pytest with a specific file path or directory passed in, we should prune the discovered test files. The fix for this issue is thus:

- Expose the filepath with which pytest was invoked to the Session: https://github.com/tophat/syrupy/blob/5eb3903afb8109bd47a6577ebff3c6d02130d998/src/syrupy/__init__.py#L62-L66
- Pass the filepath filter to the extension's discover_snapshots method: https://github.com/tophat/syrupy/blob/5eb3903afb8109bd47a6577ebff3c6d02130d998/src/syrupy/extensions/base.py#L77
- Only if pytest invoked with a filepath, prune fossils (fossil == snapshot file) before returning "discovered".

The challenge will be determining whether to prune or not. We'll have to somehow translate the discovered file to the corresponding test file -- although we might already do this somewhere? cc @iamogbz

**Comment by noahnu** [comment]
To get the list of files for which pytest was invoked, you can do something like:

```python
target_files = [
    arg for arg in config.invocation_params.args if not arg.startswith("-")
]
```

**Comment by mcataford** [comment]
I'll take a stab at this!
