### ISSUE TITLE
[Feature Request] Regex matcher

### ISSUE THREAD

**Issue by j7zAhU** [tophat/syrupy#547]
The breaking factor seems to be the last test in my file, where I serialize a dataframe :

```
string = df.to_string()
len(string)   # 2_000
assert string == snapshot
```
When I run `pytest` at the root of the test dir, I get an assertion error and the terminal displays the chunk of text.

When I selectively leave out tests, I can get this one to work. So it's not that particular serialization.

**Comment by noahnu** [comment]
Can you provide any more information, perhaps a repo where I can reproduce the issue? Or even a complete snippet of code I can copy and paste into a project to run?

Considering we have tests which cover multiple assertions and selectively running test files, from your description it sounds like it should work.

**Comment by j7zAhU** [comment]
Sure. I'll try to put something together

**Comment by noahnu** [comment]
> I get an assertion error and the terminal displays the chunk of text

It's telling you what changed. This is likely a real test failure, not a bug of any sort. The reason you're getting a whole chunk of text, is likely due to the fact that you're converting your Dict to a string before snapshotting it. That's not necessary, and means you lose out on ambr formatting, and more useful diffs.

So instead of:

```py
def test_case(snapshot):
    output_dir_structure = { key: "value" }
    assert json.dumps(outdir_dir_structure) == snapshot
```

do:

```py
def test_case(snapshot):
    output_dir_structure = { key: "value" }
    assert outdir_dir_structure == snapshot
```

If the issue is not obvious after switching away from a string, you'll need to step through the 2 tests which conflict. You likely have some sort of test pollution, where one test is affecting the other, whether it's the use of an auto-incrementer, some shared state, or improper "cleanup".

I also noticed you're snapshotting some file system paths. That's "non-deterministic" and means your snapshot will fail if run on any other machine, such as for another developer or on CI. In this case, you're interested in syrupy matchers: https://github.com/tophat/syrupy#matcher

**Comment by j7zAhU** [comment]
Thank you. 

1. In the test file, I am serializing a Pandas dataframe. If I do not use the .to_string() method, Syrupy saves each element separately which is hard to read.

2. Regarding the matcher: I did run into the problem of non-deterministic file-paths, because pytest gives you a unique numbered directory like this: `tmp_path = C:\Users\X\AppData\Local\Temp\pytest-of-X\pytest-684\test_sample0` 

If I am building a test path such as `my_path = tmp_path / "my_subdir"`, how exactly can I ignore everything to the left of the 684?

Regards

**Comment by noahnu** [comment]
Sorry about the delay, it's been busy on my end.

Hmm, support for a regex matcher would be useful here. I have a local branch with a proof of concept, when I can find some time, I'll polish it and get that merged in.

In the meantime, it's pretty much all or nothing with a value. You can either filter out the specific key, or use a matcher to expect any arbitrary string there. No way to match partial text in a string. As a temporary workaround, I'd recommend using a matcher that expects a string type, and then if you need to assert some content in the string, you do that outside of the snapshot assertion.

**Comment by j7zAhU** [comment]
thank you

**Comment by iamogbz** [comment]
> No way to match partial text in a string

Seems like this functionality can be replicated with the current matcher

```py
def test_matches_generated_string_value(snapshot, tmp_file_path):
    def my_matcher(
        data: "SerializableData", path: "PropertyPath"
    ) -> "Optional[SerializableData]":
        # use the `path` to filter out values not to be matched on, not needed here
        # assumes data is a string as file urls usually are
        return re.sub(
            r"\w+://(.*/)+dir/filename.txt",
            lambda match: match[0].replace(match[1], "<tmp-file-path>/") if match else data,
            str(data),
        )

    assert tmp_file_path == snapshot(matcher=my_matcher)
```

In the sample some things are always constant i.e. `dir/filename.txt`, the rest can be swapped so the snapshot is only matching on the partial expected path.

**Comment by noahnu** [comment]
We can probably add a simple helper for this then

**Comment by iamogbz** [comment]
Updated example with use regex enabled matcher `path_value`.
