### ISSUE TITLE
Testsuite fails with 2 snapshot failures on v4.0.1

### ISSUE THREAD

**Issue by mweinelt** [tophat/syrupy#714]
**Describe the bug**
Tests are failing on 4.0.1

```
2 snapshots failed. 262 snapshots passed. 36 snapshots unused.

Re-run pytest with --snapshot-update to delete unused snapshots.
```

**To reproduce**

1. git clone https://github.com/tophat/syrupy
2. cd syrupy
3. git checkout v4.0.1
4. poetry install
5. poetry run pytest

**Expected behavior**

Snapshots should be up to date on releases.

**Screenshots**

n/a

**Environment (please complete the following information):**

```
platform linux -- Python 3.10.9, pytest-7.2.1, pluggy-1.0.0
benchmark: 4.0.0 (defaults: timer=time.perf_counter disable_gc=False min_rounds=5 min_time=0.000005 max_time=1.0 calibration_precision=10 warmup=False warmup_iterations=100000)
rootdir: /tmp/syrupy, configfile: pyproject.toml, testpaths: tests
plugins: syrupy-4.0.1, benchmark-4.0.0, xdist-3.2.0
```

**Additional context**

Tests are working on 4.0.0.

**Comment by noahnu** [comment]
To run tests in the syrupy project, you need to use `invoke test` rather than `poetry run pytest`. We add some additional config when going through the pyinvoke task. See [CONTRIBUTING.md](https://github.com/tophat/syrupy/blob/main/CONTRIBUTING.md#local-development). You'll still see "2 snapshots failed" but the test run will return a successful status. The "2" failures aren't real failures -- we have tests which expect snapshot failures to test some error cases.

**Comment by mweinelt** [comment]
Thanks for the explanation.
