### ISSUE TITLE
Tests marked `xfail` are reported as failures

### ISSUE THREAD

**Issue by rodrigogiraoserrao** [tophat/syrupy#736]
Hey there, thanks for your work on `syrupy`!

I'm wondering if the fact that XFAIL tests are reported as failures is an intended design decision, a bug, or something you haven't contemplated yet.

The full context is from https://github.com/Textualize/textual/issues/2282 but, in short, I have a snapshot test that is marked with `xfail`:

![](https://user-images.githubusercontent.com/5621605/231783110-cb2fd213-8fbe-4746-b9fe-8e16368c256a.png)

However, at the end, I get a report saying that one snapshot test failed:

![](https://user-images.githubusercontent.com/5621605/231783032-733059ee-9ddd-429d-bba6-34bd39facfcc.png)

I expected to see a yellow warning saying that one snapshot test gave an expected failure instead of the red warning saying that the test failed, especially taking into account the confusing contrast with pytest, which happily reports that the tests passed.

**Comment by rotu** [comment]
The "snapshot failed" message is confusing, not just confined to xfail.

E.g. the below test passes but it also displays "1 snapshot failed."

```python
import random

def test_nomatch(snapshot):
    assert (random.random() != snapshot())
```

**Comment by noahnu** [comment]
@rotu 

We don't support negation. I'm not sure how negation would work with updating snapshots.

**Comment by noahnu** [comment]
Support for "failed" snapshots manifests in two ways:
- Using the pytest.xfail annotation
- Capturing the Assertion Error exception (which we do in a syrupy test itself)

In both instances, the test itself passes but Syrupy prints the failure. This is because Syrupy is determining the pass/fail immediately upon assertion (`== snapshot`). It doesn't look at the test case itself.

Here is where we collection the assertion result: https://github.com/tophat/syrupy/blob/5eee3d845cd3d3c4a47ea981911e5d4f8ebe83e0/src/syrupy/assertion.py#L305

Rather than defer the assertion result collection, I think we should be able to do a pass over the assertion results once the session completes and update any assertion results based on the state of the test case.

**Comment by rotu** [comment]
it makes sense to not support inequality and my example is quite contrived! The issue is that there are really 3 parts of a snapshot assertion:

* declaring a snapshot
* checking equality
* asserting on that equality

and I’m not clear what the semantics should be.

* if we call `snapshot()` once but never check equality, is that a problem?
* If we set `x = snapshot(*opts); assert y == x; assert z == x` does that mean the test should only pass if `y==z`?
* If we check equality but *don’t* assert on the result what should happen?

**Comment by rodrigogiraoserrao** [comment]
@noahnu Thanks for fixing this! All the best :)
